import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fitness App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a Fitness App
        </h1>
        <div className={styles.grid}>
          <a href="/about" className={styles.card}>
            <h2>About Us &rarr;</h2>
            <p>Learn more about our mission and values.</p>
          </a>
          <a href="/services" className={styles.card}>
            <h2>Services &rarr;</h2>
            <p>Discover our range of services.</p>
          </a>
          <a href="/training" className={styles.card}>
            <h2>Training &rarr;</h2>
            <p>Get started with our training programs.</p>
          </a>
          <a href="/premium" className={styles.card}>
            <h2>Premium Plans &rarr;</h2>
            <p>Unlock personalized training and diet plans.</p>
          </a>
        </div>
      </main>
    </div>
  )
}
