import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Services() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Our Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Our Services
        </h1>
        <p>
          We offer a variety of services to help you reach your fitness goals.
        </p>
      </main>
    </div>
  )
}
